python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - nosetests --with-coverage --cover -package= test_app.py

after_succes:
  - coveralls
  - codecov --token=